// Generated by scripts/generate-icons.ts — do not edit manually.

export interface IconEntry {
  name: string;
  category: string;
}

export const icons: IconEntry[] = [
  {
    "name": "Archive",
    "category": "access"
  },
  {
    "name": "Bookmark",
    "category": "access"
  },
  {
    "name": "Database",
    "category": "access"
  },
  {
    "name": "Key",
    "category": "access"
  },
  {
    "name": "Shield",
    "category": "access"
  },
  {
    "name": "Tag",
    "category": "access"
  },
  {
    "name": "Accessibility",
    "category": "accessibility"
  },
  {
    "name": "AccessibilityOff",
    "category": "accessibility"
  },
  {
    "name": "ClosedCaption",
    "category": "accessibility"
  },
  {
    "name": "Hearing",
    "category": "accessibility"
  },
  {
    "name": "HearingOff",
    "category": "accessibility"
  },
  {
    "name": "SignLanguage",
    "category": "accessibility"
  },
  {
    "name": "Visibility",
    "category": "accessibility"
  },
  {
    "name": "VisibilityOff",
    "category": "accessibility"
  },
  {
    "name": "Wheelchair",
    "category": "accessibility"
  },
  {
    "name": "Add",
    "category": "actions"
  },
  {
    "name": "Create",
    "category": "actions"
  },
  {
    "name": "Delete",
    "category": "actions"
  },
  {
    "name": "Lock",
    "category": "actions"
  },
  {
    "name": "Publish",
    "category": "actions"
  },
  {
    "name": "Refresh",
    "category": "actions"
  },
  {
    "name": "Sync",
    "category": "actions"
  },
  {
    "name": "Unlock",
    "category": "actions"
  },
  {
    "name": "ArrowDown",
    "category": "arrows"
  },
  {
    "name": "ArrowDownLeft",
    "category": "arrows"
  },
  {
    "name": "ArrowDownRight",
    "category": "arrows"
  },
  {
    "name": "ArrowLeft",
    "category": "arrows"
  },
  {
    "name": "ArrowRight",
    "category": "arrows"
  },
  {
    "name": "ArrowsHorizontal",
    "category": "arrows"
  },
  {
    "name": "ArrowUp",
    "category": "arrows"
  },
  {
    "name": "ArrowUpLeft",
    "category": "arrows"
  },
  {
    "name": "ArrowUpRight",
    "category": "arrows"
  },
  {
    "name": "ArrowVertical",
    "category": "arrows"
  },
  {
    "name": "ChevronDown",
    "category": "arrows"
  },
  {
    "name": "ChevronLeft",
    "category": "arrows"
  },
  {
    "name": "ChevronRight",
    "category": "arrows"
  },
  {
    "name": "ChevronUp",
    "category": "arrows"
  },
  {
    "name": "Building",
    "category": "buildings"
  },
  {
    "name": "Castle",
    "category": "buildings"
  },
  {
    "name": "Factory",
    "category": "buildings"
  },
  {
    "name": "Hospital",
    "category": "buildings"
  },
  {
    "name": "House",
    "category": "buildings"
  },
  {
    "name": "Office",
    "category": "buildings"
  },
  {
    "name": "School",
    "category": "buildings"
  },
  {
    "name": "Store",
    "category": "buildings"
  },
  {
    "name": "Warehouse",
    "category": "buildings"
  },
  {
    "name": "Analytics",
    "category": "charts"
  },
  {
    "name": "AreaChart",
    "category": "charts"
  },
  {
    "name": "BarChart",
    "category": "charts"
  },
  {
    "name": "Gauge",
    "category": "charts"
  },
  {
    "name": "LineChart",
    "category": "charts"
  },
  {
    "name": "PieChart",
    "category": "charts"
  },
  {
    "name": "ScatterChart",
    "category": "charts"
  },
  {
    "name": "TrendDown",
    "category": "charts"
  },
  {
    "name": "TrendUp",
    "category": "charts"
  },
  {
    "name": "Battery",
    "category": "connectivity"
  },
  {
    "name": "Bluetooth",
    "category": "connectivity"
  },
  {
    "name": "Wifi",
    "category": "connectivity"
  },
  {
    "name": "Grid",
    "category": "design"
  },
  {
    "name": "List",
    "category": "design"
  },
  {
    "name": "Emoji",
    "category": "emoji"
  },
  {
    "name": "Copy",
    "category": "files"
  },
  {
    "name": "Document",
    "category": "files"
  },
  {
    "name": "Download",
    "category": "files"
  },
  {
    "name": "Edit",
    "category": "files"
  },
  {
    "name": "Folder",
    "category": "files"
  },
  {
    "name": "FolderClosed",
    "category": "files"
  },
  {
    "name": "Link",
    "category": "files"
  },
  {
    "name": "Paste",
    "category": "files"
  },
  {
    "name": "Save",
    "category": "files"
  },
  {
    "name": "Share",
    "category": "files"
  },
  {
    "name": "Upload",
    "category": "files"
  },
  {
    "name": "FaceId",
    "category": "identity"
  },
  {
    "name": "Fingerprint",
    "category": "identity"
  },
  {
    "name": "Guest",
    "category": "identity"
  },
  {
    "name": "Incognito",
    "category": "identity"
  },
  {
    "name": "Login",
    "category": "identity"
  },
  {
    "name": "Logout",
    "category": "identity"
  },
  {
    "name": "Passkey",
    "category": "identity"
  },
  {
    "name": "Password",
    "category": "identity"
  },
  {
    "name": "Privacy",
    "category": "identity"
  },
  {
    "name": "Profile",
    "category": "identity"
  },
  {
    "name": "Register",
    "category": "identity"
  },
  {
    "name": "Security",
    "category": "identity"
  },
  {
    "name": "Session",
    "category": "identity"
  },
  {
    "name": "Users",
    "category": "identity"
  },
  {
    "name": "Verified",
    "category": "identity"
  },
  {
    "name": "Mail",
    "category": "mail"
  },
  {
    "name": "Minus",
    "category": "math"
  },
  {
    "name": "Plus",
    "category": "math"
  },
  {
    "name": "Art",
    "category": "media"
  },
  {
    "name": "Camera",
    "category": "media"
  },
  {
    "name": "Game",
    "category": "media"
  },
  {
    "name": "Headphone",
    "category": "media"
  },
  {
    "name": "Image",
    "category": "media"
  },
  {
    "name": "Microphone",
    "category": "media"
  },
  {
    "name": "Music",
    "category": "media"
  },
  {
    "name": "Pause",
    "category": "media"
  },
  {
    "name": "Play",
    "category": "media"
  },
  {
    "name": "Stop",
    "category": "media"
  },
  {
    "name": "Video",
    "category": "media"
  },
  {
    "name": "Volume",
    "category": "media"
  },
  {
    "name": "Globe",
    "category": "navigation"
  },
  {
    "name": "Home",
    "category": "navigation"
  },
  {
    "name": "Location",
    "category": "navigation"
  },
  {
    "name": "Search",
    "category": "navigation"
  },
  {
    "name": "Idea",
    "category": "productivity"
  },
  {
    "name": "Bug",
    "category": "programming"
  },
  {
    "name": "Code",
    "category": "programming"
  },
  {
    "name": "Terminal",
    "category": "programming"
  },
  {
    "name": "Gift",
    "category": "shopping"
  },
  {
    "name": "ShoppingBag",
    "category": "shopping"
  },
  {
    "name": "ShoppingCart",
    "category": "shopping"
  },
  {
    "name": "Check",
    "category": "status"
  },
  {
    "name": "Backspace",
    "category": "symbols"
  },
  {
    "name": "Enter",
    "category": "symbols"
  },
  {
    "name": "Favorite",
    "category": "symbols"
  },
  {
    "name": "Shift",
    "category": "symbols"
  },
  {
    "name": "ShiftActive",
    "category": "symbols"
  },
  {
    "name": "Star",
    "category": "symbols"
  },
  {
    "name": "Ai",
    "category": "system"
  },
  {
    "name": "Close",
    "category": "system"
  },
  {
    "name": "Filter",
    "category": "system"
  },
  {
    "name": "Menu",
    "category": "system"
  },
  {
    "name": "More",
    "category": "system"
  },
  {
    "name": "Notification",
    "category": "system"
  },
  {
    "name": "Settings",
    "category": "system"
  },
  {
    "name": "Sort",
    "category": "system"
  },
  {
    "name": "User",
    "category": "system"
  },
  {
    "name": "Calendar",
    "category": "time"
  },
  {
    "name": "Time",
    "category": "time"
  }
];

export const categories = Array.from(
  new Set(icons.map((icon) => icon.category)),
).sort();
