import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { formatSvgFromTsx } from "./format-svg";

export interface IconEntry {
  name: string;
  category: string;
  svg: string;
}

export async function discoverIconEntries(): Promise<IconEntry[]> {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const srcDir = path.resolve(scriptDir, "../../src");
  const categories = await fs.readdir(srcDir, { withFileTypes: true });
  const icons: IconEntry[] = [];

  for (const category of categories) {
    if (!category.isDirectory()) continue;

    const categoryDir = path.join(srcDir, category.name);
    const files = await fs.readdir(categoryDir);

    for (const file of files) {
      if (!file.endsWith(".tsx")) continue;

      const filePath = path.join(categoryDir, file);
      const source = await fs.readFile(filePath, "utf8");

      icons.push({
        name: path.basename(file, ".tsx"),
        category: category.name,
        svg: formatSvgFromTsx(source),
      });
    }
  }

  return icons.sort((a, b) => {
    const categoryCompare = a.category.localeCompare(b.category);
    if (categoryCompare !== 0) return categoryCompare;
    return a.name.localeCompare(b.name);
  });
}

async function main() {
  const icons = await discoverIconEntries();
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const outputPath = path.resolve(scriptDir, "../lib/icons.ts");

  const contents = `// Generated by scripts/generate-icons.ts — do not edit manually.

export interface IconEntry {
  name: string;
  category: string;
  svg: string;
}

export const icons: IconEntry[] = ${JSON.stringify(icons, null, 2)};

export const categories = Array.from(
  new Set(icons.map((icon) => icon.category)),
).sort();
`;

  await fs.writeFile(outputPath, contents);
  console.log(`Wrote ${icons.length} icons to lib/icons.ts`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
